### ISSUE TITLE
[Login] In this new version, after open the application for the first time, there's no login option

### ISSUE THREAD

**Issue by maioni** [CESARBR/corona-mission#82]
**Describe the bug**
[Login] In this new version, after open the application for the first time, there's no login option

**To Reproduce**
1. Open the application (first time)

**Expected behavior**
Login screen is displayed before user can try the application.

**Actual behavior**
Application open the home screen, with the option to register a new grandpa contact, without the login option (Something is missing)

**Screenshots**
First time opening the app:
![image](https://user-images.githubusercontent.com/6604846/81460685-5454bb00-917d-11ea-8b82-f7b9922643e5.png)

Second time opening the app:
![image](https://user-images.githubusercontent.com/6604846/81460751-b8777f00-917d-11ea-8d87-35187e86c37c.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by JoseClaudioADS** [comment]
With the removal of Firebase, features such as user registration, login and password recovery were removed. All information will be stored on the user's smartphone so that it no longer makes sense to login, etc. What remains is the team responsible for adjusting the flow in the documentation. Recalling that the demand for the removal of Firebase was extraordinary and urgent.
